"""
Dynamical Lie Algebra (DLA) computation for QAOA.
Computes the Lie algebra generated by {iC, iB} via nested commutators.

For MaxCut QAOA:
  C = sum_{(i,j)}(I - Z_i Z_j)/2  ->  iC is spanned by ZZ terms
  B = sum_i X_i                    ->  iB is spanned by X terms

Each DLA element is a Pauli string (I, X, Y, Z on each qubit).
Representation: integer tuple, 0=I, 1=X, 2=Y, 3=Z.

Key fact for Pauli strings P, Q:
  [P, Q] = P·Q - Q·P = (1 - (-1)^k) · P·Q
  where k = #positions where Pi and Qi anticommute.
  If k is odd:  [P, Q] = 2 * P·Q  (P·Q is another Pauli string up to phase)
  If k is even: [P, Q] = 0
"""

import numpy as np
import networkx as nx

PAULI_NAMES = {0: 'I', 1: 'X', 2: 'Y', 3: 'Z'}

# Multiplication table for Pauli matrices: pauli_product[i][j] = (phase, result_pauli)
# phase is 1, -1, 1j, -1j
_PAULI_PROD = {}
for i in range(4):
    for j in range(4):
        _PAULI_PROD[(i, j)] = (1, 0)  # default placeholder

# I * anything = anything
for j in range(4):
    _PAULI_PROD[(0, j)] = (1, j)
    _PAULI_PROD[(j, 0)] = (1, j)

# Same Pauli: X*X = I, Y*Y = I, Z*Z = I
for p in [1, 2, 3]:
    _PAULI_PROD[(p, p)] = (1, 0)

# X*Y = iZ,  Y*X = -iZ
_PAULI_PROD[(1, 2)] = (1j, 3)
_PAULI_PROD[(2, 1)] = (-1j, 3)

# Y*Z = iX,  Z*Y = -iX
_PAULI_PROD[(2, 3)] = (1j, 1)
_PAULI_PROD[(3, 2)] = (-1j, 1)

# Z*X = iY,  X*Z = -iY
_PAULI_PROD[(3, 1)] = (1j, 2)
_PAULI_PROD[(1, 3)] = (-1j, 2)


def _pauli_anticommute(p, q):
    """Check if two single-qubit Paulis anticommute."""
    if p == 0 or q == 0:
        return False  # identity commutes with everything
    return p != q


def _pauli_str_to_label(ps):
    return ''.join(PAULI_NAMES[p] for p in ps)


def commutator_pauli_strings(s1: tuple, s2: tuple) -> list[tuple]:
    """
    Compute [P, Q] for two Pauli strings.
    Result is either empty list (commute) or [(phase, pauli_string)].
    """
    n = len(s1)

    # Count anticommuting positions
    k = sum(1 for i in range(n) if _pauli_anticommute(s1[i], s2[i]))

    if k % 2 == 0:
        return []  # they commute

    # Compute P·Q = product at each position with accumulated phase
    phase = 1
    result = [0] * n
    for i in range(n):
        ph, res = _PAULI_PROD[(s1[i], s2[i])]
        phase *= ph
        result[i] = res

    # [P, Q] = (1 - (-1)^k) * P·Q = 2 * P·Q  when k is odd
    phase *= 2  # factor of 2 from (1 - (-1)^k)

    return [(phase, tuple(result))]


def dla_basis(graph: nx.Graph, max_iter: int = 50, verbose: bool = False) -> tuple[int, set]:
    """
    Compute DLA basis for QAOA on the given graph.
    Returns (dimension, set_of_pauli_strings).

    Initial generators:
    - iB: X_i for each qubit i
    - iC: Z_i Z_j for each edge (i,j)   [since i * (I-ZZ)/2 gives constant + iZZ]

    Note: we track the i*C generators. Constant terms (identity) are not Lie algebra
    generators since they commute with everything.
    """
    n = graph.number_of_nodes()
    basis = set()

    # Generator: X_i for each qubit (from iB = i * sum X_i)
    for i in range(n):
        s = [0] * n
        s[i] = 1
        basis.add(tuple(s))

    # Generator: Z_i Z_j for each edge (from iC = i * sum (I-ZZ)/2)
    # The ZZ term is what generates the algebra; the identity part doesn't contribute
    for u, v in graph.edges():
        s = [0] * n
        s[u] = 3
        s[v] = 3
        basis.add(tuple(s))

    if verbose:
        print(f"  Initial basis: {len(basis)} elements")
        for b in sorted(basis):
            print(f"    {_pauli_str_to_label(b)}")

    for iteration in range(max_iter):
        basis_list = list(basis)
        n_old = len(basis)
        new_basis = set(basis)

        for i, s1 in enumerate(basis_list):
            for s2 in basis_list[i + 1:]:
                comm_results = commutator_pauli_strings(s1, s2)
                for _, rs in comm_results:
                    new_basis.add(rs)

        if len(new_basis) == n_old:
            if verbose:
                print(f"  Converged at iter {iteration + 1}, dim = {n_old}")
            break

        basis = new_basis
        if verbose:
            print(f"  Iter {iteration + 1}: dim = {len(basis)}")

    return len(basis), basis


def dla_analysis(graphs: list[tuple[str, nx.Graph]], verbose: bool = False) -> list[dict]:
    """Compute DLA for a list of graphs."""
    results = []
    for name, g in graphs:
        if verbose:
            print(f"DLA for {name} (n={g.number_of_nodes()}, m={g.number_of_edges()}):")
        dim, basis = dla_basis(g, verbose=verbose)
        results.append({
            "name": name,
            "n": g.number_of_nodes(),
            "edges": g.number_of_edges(),
            "dla_dim": dim,
            "basis_labels": sorted([_pauli_str_to_label(b) for b in basis]),
        })
        if verbose:
            print(f"  DLA dim = {dim}")
    return results


def dla_density_scan(n: int, d_range: list[int], n_samples: int = 3,
                     verbose: bool = False) -> list[dict]:
    """
    Scan DLA dimension vs degree for d-regular random graphs.
    Returns [{n, d, sample, dla_dim}, ...]
    """
    from graph_families import random_regular_graph
    results = []
    for d in d_range:
        for s in range(n_samples):
            seed = 100 * d + s
            try:
                g = random_regular_graph(n, d, seed=seed)
                dim, _ = dla_basis(g)
                results.append({"n": n, "d": d, "sample": s, "dla_dim": dim})
                if verbose:
                    print(f"  n={n} d={d} s={s}: dim={dim}")
            except nx.NetworkXError:
                if verbose:
                    print(f"  n={n} d={d} s={s}: graph generation failed, skipping")
    return results


if __name__ == "__main__":
    from hamiltonian import graph_c4, graph_g6, graph_g9
    from graph_families import path_graph, cycle_graph, complete_bipartite_graph

    graphs = [
        ("C4", graph_c4()),
        ("G6", graph_g6()),
        ("G9", graph_g9()),
        ("P4", path_graph(4)),
        ("C5", cycle_graph(5)),
        ("K2_2", complete_bipartite_graph(2, 2)),
        ("K2_3", complete_bipartite_graph(2, 3)),
    ]
    results = dla_analysis(graphs, verbose=True)

    print("\n=== DLA Summary ===")
    for r in results:
        max_dim = 4 ** r["n"]
        print(f"{r['name']:8s}: n={r['n']}, |E|={r['edges']}, "
              f"DLA dim={r['dla_dim']:3d} / {max_dim} "
              f"({100 * r['dla_dim'] / max_dim:.1f}%)")
